// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Entities;


namespace Repositories;

public partial class MyShopContext : DbContext
{
    public MyShopContext() { }
    public MyShopContext(DbContextOptions<MyShopContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BasicSite> BasicSites { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CartItem> CartItems { get; set; }

    public virtual DbSet<GeminiPrompt> GeminiPrompts { get; set; }

    public virtual DbSet<MainCategory> MainCategories { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<Platform> Platforms { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<SiteType> SiteTypes { get; set; }

    public virtual DbSet<Status> Statuses { get; set; }

    public virtual DbSet<SubCategory> SubCategories { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BasicSite>(entity =>
        {
            entity.HasKey(e => e.BasicSiteId).HasName("PK__BasicSit__FFB1C800DF4A3F07");

            entity.Property(e => e.SiteName).HasMaxLength(500);
            entity.Property(e => e.SiteTypeId).HasColumnName("SiteTypeID");

            entity.HasOne(d => d.Platform).WithMany(p => p.BasicSites)
                .HasForeignKey(d => d.PlatformId)
                .HasConstraintName("FK_BasicSites_Platforms");

            entity.HasOne(d => d.SiteType).WithMany(p => p.BasicSites)
                .HasForeignKey(d => d.SiteTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BasicSites_SiteTypes");
        });

        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.CartId).HasName("PK__Carts__51BCD7B7B795F559");

            entity.HasIndex(e => e.UserId, "UQ__Carts__1788CC4D5B9FB2BD").IsUnique();

            entity.HasOne(d => d.BasicSite).WithMany(p => p.Carts)
                .HasForeignKey(d => d.BasicSiteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CartsPlatforms_BasicSites");

            entity.HasOne(d => d.User).WithOne(p => p.Cart)
                .HasForeignKey<Cart>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Carts_Users");
        });

        modelBuilder.Entity<CartItem>(entity =>
        {
            entity.HasKey(e => e.CartItemId).HasName("PK__CartItem__488B0B0AE9338F2F");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PlatformId).HasDefaultValue(1);
            entity.Property(e => e.PromptId).HasColumnName("PromptID");

            entity.HasOne(d => d.Cart).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.CartId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CartItems_Carts");

            entity.HasOne(d => d.Platform).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.PlatformId)
                .HasConstraintName("FK_CartItems_Platforms");

            entity.HasOne(d => d.Product).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CartItems_Products");

            entity.HasOne(d => d.Prompt).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.PromptId)
                .HasConstraintName("FK_CartItems_GeminiPrompt");
        });

        modelBuilder.Entity<GeminiPrompt>(entity =>
        {
            entity.HasKey(e => e.PromptId);

            entity.ToTable("GeminiPrompt");

            entity.Property(e => e.PromptId).HasColumnName("PromptID");
            entity.Property(e => e.Prompt).IsRequired();

            entity.HasOne(d => d.Product).WithMany(p => p.GeminiPrompts)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_GeminiPrompt_Products");

            entity.HasOne(d => d.SubCategory).WithMany(p => p.GeminiPrompts)
                .HasForeignKey(d => d.SubCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GeminiPrompt_SubCategory");
        });

        modelBuilder.Entity<MainCategory>(entity =>
        {
            entity.HasKey(e => e.MainCategoryId).HasName("PK__MainCate__0290BDD64C8B2AD9");

            entity.HasIndex(e => e.MainCategoryName, "UQ__MainCate__121AD3E3610F8F40").IsUnique();

            entity.Property(e => e.MainCategoryName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.MainCategoryPrompt).IsRequired();
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__C3905BCFD2B97788");

            entity.Property(e => e.OrderDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue(1);

            entity.HasOne(d => d.BasicSite).WithMany(p => p.Orders)
                .HasForeignKey(d => d.BasicSiteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_BasicSites");

            entity.HasOne(d => d.StatusNavigation).WithMany(p => p.Orders)
                .HasForeignKey(d => d.Status)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_Statuses");

            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_Users");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasKey(e => e.OrderItemId).HasName("PK__OrderIte__57ED06814D006F5C");

            entity.Property(e => e.PromptId).HasColumnName("PromptID");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItems_Orders");

            entity.HasOne(d => d.Platform).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.PlatformId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItems_Platforms");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItems_Products");

            entity.HasOne(d => d.Prompt).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.PromptId)
                .HasConstraintName("FK_OrderItems_GeminiPrompt");
        });

        modelBuilder.Entity<Platform>(entity =>
        {
            entity.HasKey(e => e.PlatformId).HasName("PK__Platform__F559F6FA4B71F28D");

            entity.HasIndex(e => e.PlatformName, "UQ__Platform__85614BEEC5A3CB06").IsUnique();

            entity.Property(e => e.PlatformName)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK__Products__B40CC6CD02C06A1F");

            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ProductPrompt).IsRequired();

            entity.HasOne(d => d.SubCategory).WithMany(p => p.Products)
                .HasForeignKey(d => d.SubCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Products_SubCategories");
        });

        modelBuilder.Entity<Rating>(entity =>
        {
            entity.ToTable("RATING");

            entity.Property(e => e.RatingId).HasColumnName("RATING_ID");
            entity.Property(e => e.Host)
                .HasMaxLength(50)
                .HasColumnName("HOST");
            entity.Property(e => e.Method)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("METHOD");
            entity.Property(e => e.Path)
                .HasMaxLength(50)
                .HasColumnName("PATH");
            entity.Property(e => e.RecordDate)
                .HasColumnType("datetime")
                .HasColumnName("Record_Date");
            entity.Property(e => e.Referer)
                .HasMaxLength(100)
                .HasColumnName("REFERER");
            entity.Property(e => e.UserAgent).HasColumnName("USER_AGENT");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__Reviews__74BC79CE1C8AA0AF");

            entity.Property(e => e.ReviewImageUrl).HasMaxLength(255);

            entity.HasOne(d => d.Order).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Review_Orders");
        });

        modelBuilder.Entity<SiteType>(entity =>
        {
            entity.HasKey(e => e.SiteTypeId).HasName("PK__SiteType__85A71CE6C5295058");

            entity.HasIndex(e => e.SiteTypeName, "UQ__SiteType__3AB6FDCA747176A1").IsUnique();

            entity.Property(e => e.SiteTypeDescriptionPrompt).IsRequired();
            entity.Property(e => e.SiteTypeName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.SiteTypeNamePrompt).IsRequired();
        });

        modelBuilder.Entity<Status>(entity =>
        {
            entity.HasKey(e => e.StatusId).HasName("PK__Statuses__C8EE206318F5FA62");

            entity.Property(e => e.StatusName).HasMaxLength(255);
        });

        modelBuilder.Entity<SubCategory>(entity =>
        {
            entity.HasKey(e => e.SubCategoryId).HasName("PK__SubCateg__26BE5B193C0BEE2E");

            entity.HasIndex(e => e.SubCategoryName, "UQ__SubCateg__0BBDA28B7CDB2B96").IsUnique();

            entity.Property(e => e.ImageUrl)
                .HasMaxLength(1000)
                .HasColumnName("ImageURL");
            entity.Property(e => e.SubCategoryName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.SubCategoryPrompt).IsRequired();

            entity.HasOne(d => d.MainCategory).WithMany(p => p.SubCategories)
                .HasForeignKey(d => d.MainCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SubCategories_MainCategories");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4C930BF82F");

            entity.HasIndex(e => e.Email, "UQ__Users__A9D10534486E6FC6").IsUnique();

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FirstName).HasMaxLength(255);
            entity.Property(e => e.LastName).HasMaxLength(255);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}