// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class BasicSitesPlatform
{
    public int BasicSitePlatformId { get; set; }

    public int? BasicSiteId { get; set; }

    public int? PlatformId { get; set; }

    public string PlatformPrompt { get; set; }

    public virtual BasicSite BasicSite { get; set; }

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual Platform Platform { get; set; }
}