// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class BasicSite
{
    public int BasicSiteId { get; set; }

    public string SiteName { get; set; }

    public int SiteTypeId { get; set; }

    public string UserDescreption { get; set; }

    public virtual ICollection<BasicSitesPlatform> BasicSitesPlatforms { get; set; } = new List<BasicSitesPlatform>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual SiteType SiteType { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}