// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class BasicSite
{
    public long BasicSiteId { get; set; }

    public string SiteName { get; set; }

    public long SiteTypeId { get; set; }

    public long? PlatformId { get; set; }

    public string UserDescreption { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Platform Platform { get; set; }

    public virtual SiteType SiteType { get; set; }
}