// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class CartItem
{
    public int CartId { get; set; }

    public int UserId { get; set; }

    public int ProductId { get; set; }

    public int BasicSitesPlatformId { get; set; }

    public bool? IsActive { get; set; }

    public string UserDescription { get; set; }

    public virtual BasicSitesPlatform BasicSitesPlatform { get; set; }

    public virtual Product Product { get; set; }

    public virtual User User { get; set; }
}