// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class CartItem
{
    public int CartItemId { get; set; }

    public int CartId { get; set; }

    public int ProductId { get; set; }

    public bool? IsActive { get; set; }

    public string UserDescription { get; set; }

    public int? PlatformId { get; set; }

    public virtual Cart Cart { get; set; }

    public virtual Platform Platform { get; set; }

    public virtual Product Product { get; set; }
}