// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class GeminiPrompt
{
    public int PromptId { get; set; }

    public string Prompt { get; set; }

    public int? ProductId { get; set; }

    public int SubCategoryId { get; set; }

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual Product Product { get; set; }

    public virtual SubCategory SubCategory { get; set; }
}