// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class MainCategory
{
    public int MainCategoryId { get; set; }

    public string MainCategoryName { get; set; }

    public string MainCategoryPrompt { get; set; }

    public virtual ICollection<SubCategory> SubCategories { get; set; } = new List<SubCategory>();
}