// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class OrderItem
{
    public long OrderItemId { get; set; }

    public long ProductId { get; set; }

    public long OrderId { get; set; }

    public long PlatformId { get; set; }

    public long? PromptId { get; set; }

    public virtual Order Order { get; set; }

    public virtual Platform Platform { get; set; }

    public virtual Product Product { get; set; }

    public virtual GeminiPrompt Prompt { get; set; }
}