// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Platform
{
    public int PlatformId { get; set; }

    public string PlatformName { get; set; }

    public virtual ICollection<BasicSitesPlatform> BasicSitesPlatforms { get; set; } = new List<BasicSitesPlatform>();
}