// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Product
{
    public long ProductId { get; set; }

    public long SubCategoryId { get; set; }

    public string ProductName { get; set; }

    public double Price { get; set; }

    public string ProductPrompt { get; set; }

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual SubCategory SubCategory { get; set; }
}