// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Review
{
    public long ReviewId { get; set; }

    public long OrderId { get; set; }

    public short Score { get; set; }

    public string ReviewImageUrl { get; set; }

    public string Note { get; set; }

    public virtual Order Order { get; set; }
}