// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class SiteType
{
    public int SiteTypeId { get; set; }

    public string SiteTypeName { get; set; }

    public double Price { get; set; }

    public string SiteTypeDescription { get; set; }

    public string SiteTypeNamePrompt { get; set; }

    public string SiteTypeDescriptionPrompt { get; set; }

    public virtual ICollection<BasicSite> BasicSites { get; set; } = new List<BasicSite>();
}