// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Status
{
    public int StatusId { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}