// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class SubCategory
{
    public int SubCategoryId { get; set; }

    public int MainCategoryId { get; set; }

    public string SubCategoryName { get; set; }

    public string SubCategoryPrompt { get; set; }

    public string ImageUrl { get; set; }

    public string CategoryDescription { get; set; }

    public virtual ICollection<GeminiPrompt> GeminiPrompts { get; set; } = new List<GeminiPrompt>();

    public virtual MainCategory MainCategory { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}